= tlp-cluster Development Guide
Jon Haddad <jon@thelastpickle.com>
:toc: left
:icons: font

Hello there.  If you're reading this, you've probably decided to contribute to tlp-cluster or use the tools for your own work.  Very cool.

INFO:: These docs are a WIP and we

== Overview

tlp-cluster is broken into several subprojects to make each compontent a bit more managable.  Some of these are docker (which are prefixed with `docker-`), some are text generation (such as the manual you're reading now), and others are simply a bit of code that download a artifact.  Each subproject is versioned and may potentially create an artifact which can be downloaded separately, such as the `dashboards` subproject.


== Docker

Each container is versioned and can be built locally using the following:

[source,bash]
----
./gradlew :PROJECT-NAME:buildDocker
----

where `PROJECT-NAME` is one of the subproject directories you see in the top level.


== Subprojects


=== docker-ssh


=== docker-grafonnet

This container


== Publishing


[source,bash]
----
./gradlew build uploadAll
----