version: "3.0"

services:
  terraform:
    build: .
    volumes:
      - "./:/local"

    working_dir: "/local"

  pssh:
    build:
      dockerfile: DockerfileSSH
      context: "."
    volumes:
      - "${SSH_KEY_PATH}:/root/.ssh/aws-private-key:ro"
      - "${PWD}:/local"
    working_dir: "/local"

  build-cassandra:
    build:
      dockerfile: DockerfileCassandra
      context: "."
    volumes:
      # fix this before merging to master
      - "${CASSANDRA_DIR}:/cassandra"
      - "${HOME}/.tlp-cluster/builds/${BUILD_NAME}:/builds"
      - "${HOME}/.tlp-cluster/maven-cache/:/root/.m2/"

    environment:
      - BUILD_NAME


