= tlp-cluster
Jon Haddad <jon@thelastpickle.com>
:toc: left
:icons: font

This is the manual for tlp-cluster, a provisioning tool for Apache Cassandra designed for developers looking to both benchmark and test the correctness of Apache Cassandra.  It assists with builds and starting instances on AWS.

== Prerequisites

There are some AWS resources tlp-cluster expects to exist:

- A security group that allows inbound SSH traffic.
- A key pair, private part of which should be present in your `~/.ssh` with `chmod 400` on it.

== Installation

The cluster provisioning tool is somewhat self explanatory (hopefully).

It launches Cassandra clusters in AWS. In addition to Cassandra, the tool can also launch stress nodes (soon) and a prometheus node to gather all the metrics.

The tool itself is written in Kotlin, leveraging Docker and Docker Compose (for now).

To get started, add the bin directory in tlp-cluster to your $PATH.  For example:

[source,bash]
----
export PATH="$PATH:/path/to/tlp-cluster/bin"
cd /path/to/tlp-cluster
./gradlew assemble
----

Now you can use the tool, yay.


== Setup

This tool requires a bit of bash and docker.  I don't know if will run on Windows.  We assume most people doing any serious Cassandra development will have access to a Linux box or virtual machine.

If you've never used to the tool before, run the tool without any parameters, `bin/tlp-cluster`.   You will be asked some questions to generate a configuration file which will be placed in your `$HOME/.tlp-cluster/user.yaml`.

IMPORTANT: We currently only support the ubuntu 16 ami in us-west-2.  We'd love a pull request to improve this!

Running the command without any arguments will print out the usage:

[source,bash]
----
tlp-cluster
----



== Initialize a Cluster

The tool uses the current working directory as a project, of sorts. To get started, run the following, substituting your customer, ticket and purpose.  This is an artifact of how we work on projects at TLP.

[source,bash]
----
tlp-cluster init CLIENT TICKET PURPOSE
----

Where:

* `CLIENT` - Name of the customer or client associated with the work you are doing with `tlp-cluster`.
* `TICKET` - Jira ticket number associated with the work you are doing with `tlp-cluster`.
* `PURPOSE` - Reason why you are creating the cluster.

This will initialize the current directory with a variables file, `terraform.tfvars` and a configuration file, terraform.tf.json. Open them up in an editor. Here you can change the number of nodes in the cluster, as well as configure the number of stress nodes you want. You can also change the instance type.

Certain instances types may not work with the ami that's hard coded.


== Launch Instances

Launch your instances with the following:

[source,bash]
----
tlp-cluster up
----

There are a few things Terraform will ask for if they are not present in `terraform.tfvars`:

[source,bash]
----
name = "Your Name"
email = "your@email.com"

# AWS profile from your ~/.aws/credentials
profile = "default"

# name of the key you intend to use for connecting to the instance
key_name = "yourkey"

# securty group the nodes should belong to
security_groups = ["yourgroup"]
----

Whether you pass these values is on the fly, or place them in the file, Terraform should eventually ask you to type `yes` and fire up your instances.

You can run arbitrary commands on all hosts:

[source,bash]
----
tlp-cluster cs ls
----


== Installing Cassandra

To install Cassandra on your instances, you will need to follow these steps:

1. Build the version you need and give it a build name (optional).
2. Select the build name you want install.
3. Install the selected build.

The first step is optional because you may already have a build in the `~/.tlp-cluster/build` directory that you want to use.

If you have no builds you will need to run the following:

[source,bash]
----
tlp-cluster build BUILD_NAME [CASSANDRA_TAG | CASSANDRA_LOCAL_REPO]
----

Where:

* `BUILD_NAME` - Name you want to give the build e.g. my-build-cass-4.0.
* `CASSANDRA_TAG` - The version number of a tagged Cassandra build e.g. `3.11.3`. Use this if you want to deploy already existing released version of Cassandra to your cluster.
* `CASSANDRA_LOCAL_REPO` - Full path to clone of the Cassandra repository. Use this if you want to deploy a custom version of Cassandra to your cluster.

If you already have a build that you would like to use you can run the following:

[source,bash]
----
tlp-cluster use BUILD_NAME
----

This will copy the binaries and configuration files to the `provisioning/cassandra` directory in your `tlp-cluster` repository. The `provisioning` directory contains a number of files that can be used to set up your instances. Being realistic, since we do so much non-standard work (EBS vs instance store, LVM vs FS directly on a device, caches, etc) we need the ability to run arbitrary commands. This isn’t a great use case for puppet / chef / salt / ansible (yet), so we are just using easy to modify scripts for now.

If you want to install other binaries or perform other operations during provisioning of the instances, you can add them to the `provisioning/cassandra` directory. Note that any new scripts you add should be prefixed with a number which is used to determine the order they are executed by the `install.sh` script.

To provision the instances run the following:

[source,bash]
----
tlp-cluster install -k SSH_KEY_PATH
----

Where:

* `SSH_KEY_PATH` - Is the full path to the private key from the key pair used when creating the instances.

This will push the contents of the `provisioning/cassandra` directory up to each of the instances you have created and install Cassandra on them.