{
 "title": "Request Overview",
 "tags": [ "cassandra" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": "label_values(cassandra_cluster)"
   },
   {
    "name": "datacenter",
    "label": "Datacenter Name",
    "query": "label_values(cassandra_datacenter)"
   },
   { "name": "rack", "label": "Rack Name", "query": "label_values(cassandra_rack)" },
   { "name": "node", "label": "Node", "query": "label_values(cassandra_node)" }
  ]
 },
 "panels": [
  { "title": "tlp-stress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reads per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    { "expr": "rate(selects_count[30s])", "legendFormat": "reads/sec" }
   ]
  },
  {
   "title": "Writes per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    { "expr": "rate(mutations_count[30s])", "legendFormat": "writes/sec" }
   ]
  },
  {
   "title": "Reads 99 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "selects{quantile=\"0.99\"}",
     "legendFormat": "reads p99"
    }
   ]
  },
  {
   "title": "Writes 99 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mutations{quantile=\"0.99\"}",
     "legendFormat": "writes p99"
    }
   ]
  },
  { "title": "cassandra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_operation_latency_seconds{cassandra_cluster=\"[[cluster]]\",cassandra_datacenter=\"[[datacenter]]\",cassandra_node=\"[[node]]\",cassandra_rack=\"[[rack]]\",instance=\"[[node]]:9500\",job=\"cassandra\",operation=\"read\",quantile=\"0.99\",table_type=\"table\",keyspace!~\"system.*\"}",
     "legendFormat": "{{cassandra_node}} {{keyspace}}.{{table}}"
    }
   ]
  }
 ]
}